### ISSUE TITLE
Derivative of assembled system with respect to coefficients

### ISSUE THREAD

**Issue by jhelgert** [IvanYashchuk/fecr#1]
I'm not sure if this is the right place to ask this kind of questions, so feel free to close this issue if needed. Since Github doesn't support latex, here's a screenshot:

<img width="571" alt="Bildschirmfoto 2020-11-11 um 13 27 59" src="https://user-images.githubusercontent.com/8471326/98811854-c904fc80-2421-11eb-9115-6278237ccdf5.png">

What I'd like to do:

- Get a python function to evaluate the assembled stiffness matrix with respect to the coefficients r_1, ..., r_nq (**without** solving the PDE)
- Get a python function to evaluate the derivative of the assembled stiffness matrix (with respect to the coefficients)

Is there any way to achieve this with your package? Since I'm new to Fenics/firedrake, I'd really appreciate any help. And sorry for this dumb question!

**Comment by IvanYashchuk** [comment]
Hey @jhelgert, I'm not quite sure that I follow what you'd like to get. What do you mean by "assembled stiffness matrix with respect to the coefficients"? Do you want [∂u/∂r₁, ∂u/∂r₂ ...]? That would not be possible without an expression for u.
The stiffness matrix is something that is usually referred to as `A_ij = a(φᵢ,φⱼ)` for the bilinear form `a`.

For the derivative of the assembled stiffness matrix wrt the r_1... coefficients
Something similar to this example https://github.com/IvanYashchuk/firedrake-numpy-adjoint/blob/master/tests/test_assemble.py should work (instead of `J_form` using the form for your stiffness matrix).

Also for all the things that do not involve calling `solve` UFL's built-in differentiation can be used. So it's possible to obtain the symbolic form for the derivative of the bilinear form wrt coefficient and then assemble it to get the concrete numerical values.
Sections 2.9.6, 2.9.7, 2.13.6 https://fenicsproject.org/pub/documents/ufl/ufl-user-manual/ufl-user-manual.pdf

There are no dumn questions and it's perfectly fine to open issues for discussions and questions. For general questions on using FEniCS and its language (UFL) I suggest using https://fenicsproject.discourse.group/ where you could get better help.

**Comment by jhelgert** [comment]
Hi @IvanYashchuk , thanks a lot for the fast and helpful response!

> I'm not quite sure that I follow what you'd like to get. What do you mean by "assembled stiffness matrix with respect to the coefficients"? Do you want [∂u/∂r₁, ∂u/∂r₂ ...]? That would not be possible without an expression for u.
The stiffness matrix is something that is usually referred to as A_ij = a(φᵢ,φⱼ) for the bilinear form a.

Actually, I want (with A = A_ij = a(φᵢ,φⱼ) )

**(I)**. The symbolic form of A as a python function of the coefficients r1, r2, ...
**(II)**. And the symbolic derivative of this function, i.e. [∂A/∂r₁, ∂A/∂r₂ ...]

Here's what a tried so far for a minimal example with q(x) = 1.0 + r1 * sin(pi * x_1) + r2 * sin(pi * x_2):


**(I)**

``` python
import numpy as np
import firedrake
import firedrake_adjoint
import ufl

def assemble_firedrake(r1, r2):
	r1 = firedrake.Constant(r1)
	r1 = firedrake.Constant(r2)
	x = firedrake.SpatialCoordinate(mesh)

	u = firedrake.TrialFunction(V)
	v = firedrake.TestFunction(V)

	# For easier notation (while keeping the namespace clean)
	dot, grad, dx = ufl.dot, ufl.grad, ufl.dx
	sin, cos, pi = ufl.sin, ufl.cos, ufl.pi

	# diffusion coefficient
	q = firedrake.Constant(1.0) + r1 * sin(pi*x[0]) + r2 * sin(pi*x[1])
	# bilinear form
	a_form = q * dot(grad(u), grad(v)) * dx
	# Homogenous Dirichlet Boundary
	u_D = firedrake.Constant(0.0)
	bc = firedrake.DirichletBC(V, u_D, "on_boundary")

	Ahandle = firedrake.assemble(a_form, bcs=bc).M.handle
	return Ahandle.convert("dense").getDenseArray()
```

With mesh and function space:

``` python
nx, ny = 3, 3
mesh = firedrake.UnitSquareMesh(nx, ny, reorder=False)
V = firedrake.FunctionSpace(mesh, "CG", 1)
```

For r1 = r2 = 0.0 we get the linear poisson problem, so it seems to be a good idea to use this as a test case:

```
print(assemble_firedrake(0.0, 0.0))
print(assemble_firedrake(0.0, 0.0))
print(assemble_firedrake(0.0, 0.0))
```

What's **really** strange: For the first two calls the output is right, but for the third call it's the zero matrix.

**(II)**

``` python
def assemble_firedrake_derivative(r1, r2):
	#r1 = firedrake.Constant(r1)
	#r2 = firedrake.Constant(r2)
	x = firedrake.SpatialCoordinate(mesh)

	u = firedrake.TrialFunction(V)
	v = firedrake.TestFunction(V)

	# For easier notation (while keeping the namespace clean)
	dot, grad, dx = ufl.dot, ufl.grad, ufl.dx
	sin, cos, pi = ufl.sin, ufl.cos, ufl.pi

	# Variable for the derivative
	r = firedrake.VectorConstant(mesh, 2)
	w = firedrake.variable(r)

        #r[0] = r1  TypeError 'Constant' object does not support item assignment
        #r[1] = r2 TypeError 'Constant' object does not support item assignment

	# Diffusion coefficient
	q = firedrake.Constant(1.0) + r[0] * sin(pi*x[0]) + r[1] * sin(pi*x[1])

	# bilinear Form
	a_form = q * dot(grad(u), grad(v)) * dx
	# Derivative?
	dF = firedrake.diff(a_form, w)

	# Homogenous Dirichlet Boundary, i.e. u = u_D = 0 on the boundary
	u_D = firedrake.Constant(0.0)
	bc = firedrake.DirichletBC(V, u_D, "on_boundary")

	return firedrake.assemble(dF, bcs=bc).M.handle.convert("dense").getDenseArray()
```
Here I don't really know how to assign the values of the function arguments r1, r2 to the VectorConstant r.

I already checked the ufl documentation but couldn't find a suited example. Tbh, I'm still a bit lost there. So any help is really appreciated.


> There are no dumn questions, and it's perfectly fine to open issues for discussions and questions. For general questions on using FEniCS and its language (UFL), I suggest using https://fenicsproject.discourse.group/ where you could get better help.

I asked a similar question (with fenics instead of firedrake) there 15 days ago. Unfortunately, without any response. :/ 
Since I want to use firedrake (and I've rather got the impression my question isn't really related to your package): Do you know any site where I could ask for help? I only found a slack channel or mailing list for development discussion, so not really the right place to ask beginner questions. And on stackoverflow there isn't even a ufl or firedrake tag.

**Comment by jhelgert** [comment]
I got it working. Thanks again! And sorry for this off-topic issue.
