### ISSUE TITLE
Complex numbers support

### ISSUE THREAD

**Issue by IvanYashchuk** [IvanYashchuk/fecr#14]
Currently, it's hardcoded that we're working only with `numpy.float64` types. However, Firedrake can be compiled to work with complex numbers as well.
I should look into what's needed to be done to enable complex numbers here.

Complex numbers version of Firedrake can be installed with `firedrake-install --complex`

**Comment by rckirby** [comment]
Thanks, we've got generalizing to work around your restriction on our Issue.  But we still need to check out complex numbers, and I recall that doing adjoints with complex has some wrinkles.

**Comment by IvanYashchuk** [comment]
Are these wrinkles related to Wirtinger derivatives?

**Comment by rckirby** [comment]
Not sure what the details are internally to UFL, other than that conjugates are non-differentiable.  I don't know the current status of support for complex adjoints in UFL/Firedrake/FEniCS

**Comment by Re-GeorX** [comment]
Hi Ivan, I see that you made the changes to delete the restriction of using np.float64, however in the line  https://github.com/IvanYashchuk/fecr/blob/289a6c472b389d928a3e80a5472f356c4eb7525e/fecr/helpers.py#L58 there's still a TypeError check that will keep restricting from using other data type. May you take a look at this? Thanks!
